#Author: Samuele Giuli
#Revised by: Adriano Amaricci
name: Scheduled CI SciFortran workflow for MacOS

on: workflow_dispatch
# on:
#   push:
#     branches:
#       - master

defaults:
  run:
    shell: bash -l {0}

jobs:
  test-QcmP:
    runs-on: macos-latest
    strategy:
      fail-fast: false

    steps:

#********* SETUP PART **********

# Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main

# Setup OS
      - uses: ./.github/actions
        with:
          pack-type: open


#********* BUILD PART **********

# Build SciFortran
      - name: Cloning SciFortran
        run: git clone https://github.com/SciFortran/SciFortran.git scifor
      - name: Install SciFortran
        run: bin/ci_setup_scifor.sh



#******** TESTING PART ********

# Testing
      - name: Building tests
        run:  |
          source ~/.scifor_config_user
          export PKG_CONFIG_PATH=~/.pkgconfig.d
          export GLOB_INC=$( pkg-config --cflags scifor)
          export GLOB_LIB=$( pkg-config --libs   scifor | sed  "s/;/ /g"  | sed 's/\\/  /g' )
          cd test
          make all

      - name: Testing...
        run: |
          cd test
          make test
